# Generated by Django 4.2 on 2024-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="enrollment_no",
            field=models.CharField(max_length=20),
        ),
    ]
