"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'assignments')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-a-%1scm%)-2qmo6&xo^&0e-06@0p+13ntb%uq*lg^vn7!z1agm"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Change the duration as needed
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Change the duration as needed
    # Other settings can go here
}
SESSION_COOKIE_AGE = 3600  # Time in seconds


SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Add Channeli OAuth settings
CHANNELI_CLIENT_ID = '0Gz474nCddLektyVZzqU1Zk9CxTRYOOcS0Css0d0'
CHANNELI_CLIENT_SECRET='miR8oyJEuL8Rl0qThH3LCGDLgnogdGDk8MhzsVK79WBgoQXcQsPDIb8hMAW4orUI5Z8VYNfYlVNc6vlQIYXZH5GGT4aE8g5XzvuYMJ2lQYZvDzg3ZmtputBKxoV9FSbF'
CHANNELI_REDIRECT_URI = 'https://localhost:8000/oauth/callback'
CHANNELI_AUTH_URL = 'https://channeli.in/oauth/authorize'
CHANNELI_TOKEN_URL = 'https://channeli.in/oauth/token'
CHANNELI_PROFILE_URL = 'https://channeli.in/open_auth/get_user_data/'

# Allow the redirect URI in allowed hosts
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'checkapp',
    'rest_framework',
    'corsheaders',
     'rest_framework.authtoken',
     # ... other installed apps
    'rest_framework_simplejwt',
    'channels'
    ]
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],  # Ensure Redis is running
        },
    },
}

# ASGI_APPLICATION = 'backend.asgi.application'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # 
]
ASGI_APPLICATION='backend.asgi.application'
CORS_ALLOW_ALL_ORIGINS = True
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ]
}
CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
      'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'autumn1',  
        'USER': 'postgres',
        'PASSWORD': '@Thiruv0nam',
        'HOST': '127.0.0.1', 
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]
AUTH_USER_MODEL = 'checkapp.User'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

