# Generated by Django 5.1.2 on 2024-11-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0002_alter_user_enrollment_no"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("assignment", "reviewee")},
        ),
    ]
