# Generated by Django 5.1.2 on 2024-11-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0003_alter_submission_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="members",
            new_name="member_ids",
        ),
    ]
