# Generated by Django 5.1.2 on 2024-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0004_rename_members_group_member_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
