# Generated by Django 5.1.2 on 2024-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
