# Generated by Django 5.1.2 on 2024-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
