# Generated by Django 4.2 on 2024-11-02 10:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0008_remove_group_member_ids_remove_user_rolenames_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
