# Generated by Django 4.2 on 2024-11-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0009_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="reviewee_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
