# Generated by Django 4.2 on 2024-11-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0010_submission_reviewee_comment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=set(),
        ),
    ]
