# Generated by Django 4.2 on 2024-11-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0012_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=30,
            ),
        ),
    ]
