# Generated by Django 4.2 on 2024-11-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0013_alter_subtask_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[("unchecked", "Unchecked"), ("checked", "Checked")],
                default="unchecked",
                max_length=30,
            ),
        ),
    ]
