# Generated by Django 5.1.2 on 2024-12-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkapp", "0014_alter_submission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="assignments",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_groups", to="checkapp.assignment"
            ),
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="group",
        ),
        migrations.AddField(
            model_name="assignment",
            name="group",
            field=models.ManyToManyField(
                related_name="assigned_assignments", to="checkapp.group"
            ),
        ),
    ]
